# Generated by Django 5.1.1 on 2024-09-19 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('location_spot', models.CharField(blank=True, max_length=50)),
                ('location_radius', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(blank=True, max_length=200)),
                ('shift_time_in', models.TimeField(null=True)),
                ('shift_time_out', models.TimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
            },
        ),
        migrations.CreateModel(
            name='User_Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_avatar', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('user_payout', models.CharField(max_length=500, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_absen_backend.location')),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_absen_backend.role')),
                ('user_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_absen_backend.shift')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
