# Generated by Django 5.1.1 on 2024-09-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_absen_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_time_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_time_out',
            field=models.TimeField(null=True),
        ),
    ]
