# Generated by Django 4.2.16 on 2024-09-30 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_absen_backend', '0003_alter_user_id_user_location_alter_user_id_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_id',
            old_name='user_name',
            new_name='name',
        ),
    ]
