# Generated by Django 4.2.16 on 2024-09-30 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_absen_backend', '0004_rename_user_name_user_id_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_avatar', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('employee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_payout', models.CharField(blank=True, max_length=500, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_absen_backend.location')),
                ('user_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_absen_backend.role')),
                ('user_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_absen_backend.shift')),
            ],
            options={
                'verbose_name': 'Employe',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_absen_backend.employee'),
        ),
        migrations.DeleteModel(
            name='User_Id',
        ),
    ]
